const mySeoMatcher = [
  {
    0: [
      'find',
      'real',
      'estate',
      'homes',
      'sale',
      'apartments',
      'houses',
      'rent',
      'realtorsearch',
      'real',
      'estate',
      'property',
      'records',
      'houses',
      'condos',
      'land',
      'find',
      'property',
      'info',
      'most',
      'comprehensive',
      'source',
      'home',
      'data',
      'online'
    ],
    1: [
      'movers',
      'local',
      'long',
      'distance',
      'moving',
      'servicesfind',
      'best',
      'quotes',
      'prices',
      'hundreds',
      'national',
      'movers',
      'cross',
      'country',
      'moves',
      'truck',
      'rentals',
      'auto',
      'transport',
      'moving.com',
      'make',
      'your',
      'next',
      'move',
      'easy'
    ],
    2: [
      'senior',
      'housing',
      'living',
      'apartmentsfind',
      'senior',
      'living',
      'independent',
      'assisted',
      'nursing',
      'homes',
      'retirement',
      'communities',
      'apartments',
      'care',
      'seniorhousingnet'
    ],
    3: ['real', 'estate', 'crm', 'software', 'top', 'producer', 'systems']
  }
];

export default mySeoMatcher;